{
  parserClass="org.rhai.RhaiParser"
  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Rhai"
  psiImplClassSuffix="Impl"
  psiPackage="org.rhai"
  psiImplPackage="org.rhai.impl"

  elementTypeHolderClass="org.rhai.RhaiTypes"
  elementTypeClass="org.rhai.psi.RhaiElementType"
  tokenTypeClass="org.rhai.psi.RhaiTokenType"

  consumeTokenMethod(".*")="consumeToken"

  tokens = [
    // Скобки и пунктуация
    LPAREN='('
    RPAREN=')'
    LBRACKET='['
    RBRACKET=']'
    LBRACE='{'
    RBRACE='}'
    SEMICOLON=';'
    COMMA=','
    DOT='.'
    COLON=':'
    QUESTION='?'
    AT='@'
    HASH='#'
    DOLLAR='$'
    TILDE='~'

    // Операторы
    PLUS='+'
    MINUS='-'
    MUL='*'
    DIV='/'
    MOD='%'
    NOT='!'
    ASSIGN='='
    LT='<'
    GT='>'
    BAND='&'
    BOR='|'
    BXOR='^'

    // Составные операторы
    ARROW='=>'
    THIN_ARROW='->'
    LEFT_ARROW='<-'
    DOUBLE_COLON='::'
    POW='**'
    RANGE='..'
    DOT_DOT_EQ='..='
    NULL_COALESCING='??'
    SPACESHIP='<=>'
    SHL='<<'
    SHR='>>'
    LE='<='
    GE='>='
    EQ='=='
    NE='!='
    AND='&&'
    OR='||'
    PLUS_ASSIGN='+='
    MINUS_ASSIGN='-='
    MUL_ASSIGN='*='
    DIV_ASSIGN='/='
    MOD_ASSIGN='%='
    AND_ASSIGN='&='
    OR_ASSIGN='|='
    XOR_ASSIGN='^='
    SHL_ASSIGN='<<='
    SHR_ASSIGN='>>='
    POW_ASSIGN='**='

    // Ключевые слова
    FN='fn'
    PRIVATE='private'
    PUB='pub'
    CONST='const'
    LET='let'
    IF='if'
    ELSE='else'
    SWITCH='switch'
    DEFAULT='default'
    RETURN='return'
    THROW='throw'
    TRY='try'
    CATCH='catch'
    FOR='for'
    IN='in'
    IS='is'
    AS='as'
    LOOP='loop'
    DO='do'
    WHILE='while'
    UNTIL='until'
    BREAK='break'
    CONTINUE='continue'
    IMPORT='import'
    EXPORT='export'
    MODULE='module'
    THIS='this'
    GLOBAL='global'
    TRUE='true'
    FALSE='false'
    NULL='null'
    UNDEF='undefined'
    SHARED='shared'
    SYNC='sync'
    ASYNC='async'
    AWAIT='await'
    INF='inf'
    NEG_INF='-inf'
    NAN='NaN'

    // Динамические токены
    IDENTIFIER
    INTEGER_LITERAL
    FLOAT_LITERAL
    STRING_LITERAL
    RAW_STRING_LITERAL
    MULTILINE_STRING_LITERAL
    CHAR_LITERAL
    REGEX_LITERAL
    SHEBANG
    BUILTIN
    INTERPOLATED_TEXT

    // Комментарии
    LINE_COMMENT
    BLOCK_COMMENT
    DOC_COMMENT
    DOC_LINE

    // Интерполированные строки
    INTERPOLATED_START='`'
    INTERPOLATED_END='`'
    INTERPOLATED_EXPR_START='${'
    INTERPOLATED_EXPR_END  // No '=' to avoid conflict with RBRACE

    // Bad character
    BAD_CHARACTER
  ]
}

/* === Грамматика === */

rhaiFile ::= SHEBANG? (attribute_list? top_level_item)*

private top_level_item ::= module_declaration
                         | function_definition
                         | import_statement
                         | export_statement
                         | statement
                         | SEMICOLON
                         | dummy_comment_tokens

// Атрибуты
attribute_list ::= HASH LBRACKET attribute (COMMA attribute)* RBRACKET
attribute ::= IDENTIFIER (LPAREN literal_value (COMMA literal_value)* RPAREN)?

// Модули
module_declaration ::= MODULE IDENTIFIER LBRACE top_level_item* RBRACE

// Import/Export
import_statement ::= IMPORT import_path (AS IDENTIFIER)? SEMICOLON?
                   | IMPORT import_path DOUBLE_COLON MUL SEMICOLON?
                   | IMPORT string_expr AS IDENTIFIER SEMICOLON?

import_path ::= IDENTIFIER (DOUBLE_COLON IDENTIFIER)*

export_statement ::= EXPORT (function_definition | const_declaration | let_declaration | MODULE IDENTIFIER)

// Function definition
function_definition ::= attribute_list? visibility? FN IDENTIFIER LPAREN parameters? RPAREN return_type? (block | SEMICOLON)
visibility ::= PRIVATE | PUB
return_type ::= ARROW type_annotation

parameters ::= parameter (COMMA parameter)* COMMA?
parameter ::= pattern (COLON type_annotation)?
type_annotation ::= type_name (LT type_annotation (COMMA type_annotation)* GT)?
type_name ::= 'int' | 'float' | 'bool' | 'string' | 'Array' | 'Map' | 'Fn' | IDENTIFIER

// Statements
statement ::= let_declaration
            | const_declaration
            | expression_statement
            | if_statement
            | switch_expression
            | while_statement
            | do_while_statement
            | until_statement
            | loop_statement
            | for_statement
            | break_statement
            | continue_statement
            | return_statement
            | throw_statement
            | try_catch_statement
            | labeled_statement
            | block

// Variable declarations
let_declaration ::= visibility? LET pattern (COLON type_annotation)? (ASSIGN expression)? SEMICOLON?
const_declaration ::= visibility? CONST pattern (COLON type_annotation)? (ASSIGN expression)? SEMICOLON?
pattern ::= IDENTIFIER
          | '_'
          | literal_value
          | LBRACKET pattern (COMMA pattern)* RBRACKET
          | LBRACE field_pattern (COMMA field_pattern)* RBRACE
field_pattern ::= IDENTIFIER (COLON pattern)?

// Labeled statements
labeled_statement ::= label COLON statement
label ::= IDENTIFIER | string_expr

// Control flow
if_statement ::= IF expression block (ELSE (if_statement | block))?
switch_expression ::= SWITCH expression LBRACE switch_arm* default_arm? RBRACE
switch_arm ::= pattern (COMMA pattern)* (IF expression)? ARROW (expression | block) COMMA?
default_arm ::= DEFAULT ARROW (expression | block) COMMA?

while_statement ::= WHILE expression block
do_while_statement ::= DO block WHILE expression SEMICOLON?
until_statement ::= UNTIL expression block
loop_statement ::= LOOP block
for_statement ::= FOR pattern IN expression block

break_statement ::= BREAK (expression | IDENTIFIER)? SEMICOLON?
continue_statement ::= CONTINUE SEMICOLON?
return_statement ::= RETURN expression? SEMICOLON?
throw_statement ::= THROW expression SEMICOLON?
try_catch_statement ::= TRY block (CATCH LPAREN pattern RPAREN block)+

block ::= LBRACE statement* RBRACE

// Literals (ЗДЕСЬ БЫЛО string_literal, СТАЛО string_expr)
literal_value ::= INTEGER_LITERAL
                | FLOAT_LITERAL
                | string_expr
                | CHAR_LITERAL
                | boolean_literal
                | REGEX_LITERAL

// Правило переименовано из string_literal в string_expr, чтобы избежать
// конфликта с токеном STRING_LITERAL (Grammar Kit создает константу для правила в верхнем регистре)
string_expr ::= STRING_LITERAL | RAW_STRING_LITERAL | MULTILINE_STRING_LITERAL
boolean_literal ::= TRUE | FALSE

// Expressions
expression ::= assignment_expr

assignment_expr ::= null_coalescing_expr assignment_rest?
assignment_rest ::= assignment_op assignment_expr
assignment_op ::= ASSIGN | PLUS_ASSIGN | MINUS_ASSIGN | MUL_ASSIGN | DIV_ASSIGN | MOD_ASSIGN | AND_ASSIGN | OR_ASSIGN | XOR_ASSIGN | SHL_ASSIGN | SHR_ASSIGN | POW_ASSIGN

null_coalescing_expr ::= conditional_expr (NULL_COALESCING conditional_expr)*

conditional_expr ::= logical_or_expr (QUESTION expression COLON conditional_expr)?

logical_or_expr ::= logical_and_expr (OR logical_and_expr)*
logical_and_expr ::= equality_expr (AND equality_expr)*

equality_expr ::= relational_expr ((EQ | NE) relational_expr)*
relational_expr ::= range_expr ((LT | GT | LE | GE | IS | IN | NOT IS | NOT IN) range_expr)*

range_expr ::= bitwise_or_expr (RANGE bitwise_or_expr (DOT_DOT_EQ bitwise_or_expr)?)?

bitwise_or_expr ::= bitwise_xor_expr (BOR bitwise_xor_expr)*
bitwise_xor_expr ::= bitwise_and_expr (BXOR bitwise_and_expr)*
bitwise_and_expr ::= shift_expr (BAND shift_expr)*

shift_expr ::= additive_expr ((SHL | SHR) additive_expr)*

additive_expr ::= multiplicative_expr ((PLUS | MINUS) multiplicative_expr)*
multiplicative_expr ::= power_expr ((MUL | DIV | MOD) power_expr)*

power_expr ::= unary_expr (POW power_expr)?

unary_expr ::= (NOT | MINUS | PLUS | MUL | BAND | QUESTION)* postfix_expr

postfix_expr ::= primary_expr postfix_op*
postfix_op ::= LPAREN argument_list? RPAREN QUESTION?
             | DOT IDENTIFIER (QUESTION | NOT)?
             | LBRACKET expression RBRACKET (QUESTION | NOT)?
             | QUESTION

argument_list ::= expression (COMMA expression)* COMMA?

primary_expr ::= literal_value
               | path_expression
               | IDENTIFIER
               | THIS
               | GLOBAL
               | LPAREN expression? RPAREN
               | array_literal
               | object_literal
               | closure_expr
               | interpolated_string
               | if_expression
               | switch_expression
               | macro_invocation

// If as expression (returns value)
if_expression ::= IF expression block (ELSE (if_expression | block))?

path_expression ::= IDENTIFIER (DOUBLE_COLON IDENTIFIER)+

array_literal ::= LBRACKET array_elements? RBRACKET
array_elements ::= expression (COMMA expression)* COMMA?
                  | expression SEMICOLON expression

object_literal ::= HASH LBRACE object_fields? RBRACE
object_fields ::= object_field (COMMA object_field)* COMMA?
object_field ::= (IDENTIFIER | string_expr | computed_property) COLON expression
               | spread_expr
computed_property ::= LBRACKET expression RBRACKET
spread_expr ::= '...' expression

closure_expr ::= BOR closure_params? BOR (block | expression)
closure_params ::= closure_param (COMMA closure_param)* COMMA?
closure_param ::= pattern (COLON type_annotation)?

interpolated_string ::= INTERPOLATED_START interpolated_part* INTERPOLATED_END
interpolated_part ::= INTERPOLATED_TEXT
                    | INTERPOLATED_EXPR_START expression INTERPOLATED_EXPR_END

macro_invocation ::= IDENTIFIER NOT macro_input?
macro_input ::= LPAREN macro_args? RPAREN
              | LBRACKET macro_args? RBRACKET
              | LBRACE macro_args? RBRACE
macro_args ::= macro_arg (COMMA macro_arg)* COMMA?
macro_arg ::= expression | IDENTIFIER COLON expression

expression_statement ::= expression SEMICOLON?

// Dummy правила для генерации токенов
private dummy_comment_tokens ::= LINE_COMMENT | BLOCK_COMMENT | DOC_COMMENT | DOC_LINE
private dummy_bad_char ::= BAD_CHARACTER